app/app/urls.py
from django.urls import include, path

urlpatterns = [
    path("", include("index.urls")),
]

app/index/urls.py
from django.urls import path
from . import views

app_name = "index"
urlpatterns = [
    path("", views.index, name="index"),
    path("contribute/", views.contribute, name="contribute"),
    path("movie/<int:movieid>/", views.movie, name="movie")
]

app/index/models.py
from django.db import models

class Movie(models.Model):
    movieid = models.IntegerField()
    title = models.CharField(max_length=100)
    year = models.IntegerField()
    genres = models.CharField(max_length=100)
    duration = models.IntegerField()
    director = models.CharField(max_length=100)
    writer = models.CharField(max_length=100)
    producer = models.CharField(max_length=100)
    starring = models.CharField(max_length=500)
    sources = models.JSONField()

class Review(models.Model):
    movieid = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.IntegerField()
    text = models.CharField(max_length=500)
    source = models.CharField(max_length=100)
    url = models.URLField(max_length=100)

app/index/forms.py
from django import forms

class MovieForm(forms.Form):
    title = forms.CharField(required=True, max_length=100, label="Title")
    year = forms.IntegerField(required=True, min_value=1900, max_value=2100, label="Year of release")
    genres = forms.CharField(required=True, max_length=100, label="Genres")
    duration = forms.IntegerField(required=False, min_value=0, max_value=1000, label="Running time")
    director = forms.CharField(required=False, max_length=100, label="Director")
    writer = forms.CharField(required=False, max_length=100, label="Writer")
    producer = forms.CharField(required=False, max_length=100, label="Producer")
    starring = forms.CharField(required=False, max_length=500, label="Starring")
    sources = forms.CharField(required=False, max_length=1000, label="Additional source links")

app/index/views.py
from django.http import HttpResponse
from random import sample
from django.template import loader
from .source_tools import get_source_json
from .models import Movie, Review
from .forms import MovieForm

def index(request):
    movies = Movie.objects.order_by("movieid")
    movie_sample_indices = sample(range(len(movies)), 5) if len(movies) > 5 else [i for i in range(len(movies))]
    movie_sample = [movies[i] for i in movie_sample_indices]
    template = loader.get_template("index/index.html")
    context = {
        "movie_count": len(movies),
        "movie_sample": movie_sample,
    }
    return HttpResponse(template.render(context, request))

def contribute(request):
    if request.method == "POST":
        form_data = MovieForm(request.POST)
        template = loader.get_template("index/contribute.html")
        context = {
            "status": "success",
            "form": form_data,
        }
        if form_data.is_valid():
            new_id = Movie.objects.order_by("-movieid")[0].movieid + 1 if len(Movie.objects.all()) > 0 else 0
            movie = Movie(
                movieid = new_id,
                title = form_data.cleaned_data["title"],
                year = form_data.cleaned_data["year"],
                genres = form_data.cleaned_data["genres"],
                duration = form_data.cleaned_data["duration"],
                director = form_data.cleaned_data["director"],
                writer = form_data.cleaned_data["writer"],
                producer = form_data.cleaned_data["producer"],
                starring = form_data.cleaned_data["starring"],
                sources = get_source_json(form_data.cleaned_data["sources"])
            )
            movie.save()
        else:
            context["status"] = "failure"
        return HttpResponse(template.render(context, request))
    else:
        template = loader.get_template("index/contribute.html")
        context = {
            "status": "none",
            "form": MovieForm(),
        }
        return HttpResponse(template.render(context, request))

def movie(request, movieid):
    template = loader.get_template("index/movie.html")
    context = {
        "movie": Movie.objects.filter(movieid=movieid)[0],
        "reviews": Review.objects.filter(movieid=movieid),
    }
    return HttpResponse(template.render(context, request))

app/index/templates/index/contribute.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Contribute to the database | Obscura</title>
        <meta name="description" content="Contribute to the database by adding new movies.">
    </head>
    <body>
        <header>
            <h1><a href="{% url 'index:index' %}">Obscura</a></h1>
            <h5>One of the aggregators of all time!</h5>
        </header>
        <h2>Contribute to the database</h2>
        <p>Please use the form below to provide information about the movie you want to add.</p>
        <form action="{% url 'index:contribute' %}" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div>
                    {{ field.label_tag }} {{ field }}
                </div>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Submit">
        </form>
        {% if status == "success" %}
        <p><b>Your entry has been successfully recorded. We appreciate the effort.</b></p>
        {% elif status == "failure" %}
        <p><b>There was an error while trying to process your entry and no data was saved.</b></p>
        {% endif %}
    </body>
</html>

app/index/templates/index/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Main page | Obscura</title>
        <meta name="description" content="Obscura - One of the aggregators of all time!">
    </head>
    <body>
        <header>
            <h1><a href="{% url 'index:index' %}">Obscura</a></h1>
            <h5>One of the aggregators of all time!</h5>
        </header>
        <h2>Overview</h2>
        {% if movie_count %}
            {% if movie_count > 5 %}
                <p>Our database is currently housing {{movie_count}} entries! Some examples below:</p>
            {% else %}
                <p>Our database is currently housing {{movie_count}} entries! They are:</p>
            {% endif %}
            <ul>
            {% for movie in movie_sample %}
                <li><a href="{% url 'index:movie' movie.movieid %}">{{ movie.title }} ({{ movie.year }})</a></li>
            {% endfor %}
            </ul>
            <p>Become a part of the project by <a href="/contribute">adding new movies</a>!</p>
        {% else %}
            <p>Our database is empty at the moment, but you can contribute by <a href="/contribute">adding new movies</a>!</p>
        {% endif %}
    </body>
</html>

app/index/templates/index/movie.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{ movie.title }} ({{ movie.year }}) | Obscura</title>
        <meta name="description" content="Information about {{ movie.title }} ({{ movie.year }}) movie.">
    </head>
    <body>
        <header>
            <h1><a href="{% url 'index:index' %}">Obscura</a></h1>
            <h5>One of the aggregators of all time!</h5>
        </header>
        <h2>Information</h2>
        <ul>
            <li>
                <p><b>Title:</b> {{ movie.title }}</p>
            </li>
            <li>
                <p><b>Year of release:</b> {{ movie.year }}</p>
            </li>
            <li>
                <p><b>Genres:</b> {{ movie.genres }}</p>
            </li>
            <li>
                <p><b>Running time:</b> {{ movie.duration }} minutes</p>
            </li>
            <li>
                <p><b>Credits</b></p>
                <ul>
                    <li>
                        <p><b>Director:</b> {{ movie.director }}</p>
                    </li>
                    <li>
                        <p><b>Writer:</b> {{ movie.writer }}</p>
                    </li>
                    <li>
                        <p><b>Producer:</b> {{ movie.producer }}</p>
                    </li>
                    <li>
                        <p><b>Starring:</b> {{ movie.starring }}</p>
                    </li>
                </ul>
            </li>
            <li>
                <p><b>Aggregated sources:</b><p>
                <ul>
                    {% for source in movie.sources %}
                    <li>
                        {% if source.code %}
                        <p><a href="{{ source.url }}">{{ source.name }}</a></p>
                        {% else %}
                        <p>Local information and reviews</p>
                        {% endif %}
                    </li>
                    {% endfor %}
                    </p><a href="{{ entry.url }}">{{ entry.source }}</a></p>
                </ul>
            </li>
        </ul>
        <h2>Reviews</h2>
        {% if reviews %}
        {% for review in reviews %}
        <div>
            <h5><b>Rating:</b> {{ review.rating}}/10</h5>
            {% if review.text %}
            <p>{{ review.text }}</p>
            {% else %}
            <p><b>This review has no text!</b></p>
            {% endif %}
            <p>(from <a href="{{ review.url }}">{{ review.source }}</a>)</p>
        </div>
        {% endfor %}
        {% else %}
        <div>
            <p><b>There are currently no reviews for this movie!</b></p>
        </div>
        {% endif %}
    </body>
</html>